/*
   Bonilla Silva Isaac
   1CM8
   PP13101211
   Libreria de la funcion Portada
 */
   #include<stdio.h>
   #include<conio.h>
   void caratula(void);
   void main(void)
	{
		clrscr();
		caratula();
		getch();
	}
   void caratula(void)
   	{
		printf("\n\n\n\t\t\t  *INSTITUTO POLITECNICO NACIONAL*");
		printf("\n\n\t\tEscuela Superior de Ingenieria Mecanica y Electrica");
		printf("\n\n\t\t  Unidad Profesional Adolfo Lopez Mateos Zacatenco");
		printf("\n\n\t\t\   Ingenieria en Comunicaciones y Electronica");
		printf("\n\n\n\n\t\t\t   *FUNDAMENTOS DE PROGRAMACION*");
        printf("\n\n\t\t\t PROFESORA: Cuellar Mercado Miriam");
		printf("\n\n\t\t\t   ALUMNO: Bonilla Silva Isaac");
		printf("\n\n\t\t\t        BOLETA:  PP13101211");
        printf("\n\n\t\t\t           GRUPO:  1CM8");
    }