/*
   Bonilla Silva Isaac
   1CM8
   2013300995
   Libreria de la funcion Portada
 */
   void caratula(void)
   	{
		printf("\n\n\n\n\n\n\t\t\t  *INSTITUTO POLITECNICO NACIONAL*\n");
		printf("\n\n\t\tEscuela Superior de Ingenieria Mec nica y El‚ctrica");
		printf("\n\n\t\t  Unidad Profesional Adolfo L¢pez Mateos Zacatenco");
		printf("\n\n\t\t\   Ingenieria en Comunicaciones y Electr¢nica");
		printf("\n\n\n\n\t\t\t   *FUNDAMENTOS DE PROGRAMACION*\n");

		printf("\n\n\t\t\t PROFESORA: Cuellar Mercado Miriam");
		printf("\n\n\t\t\t   ALUMNO: Bonilla Silva Isaac");
		printf("\n\n\t\t\t        BOLETA:  2013300995");
		printf("\n\n\t\t\t           GRUPO:  1CM8");
    }